name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write
      pull-requests: write
      statuses: write

    steps:
      - uses: actions/checkout@v4

      - name: Build and Deploy
        uses: dcilke/sanity-actions/build-and-deploy@v0.0.8
        with:
          token: ${{ secrets.SANITY_AUTH_TOKEN }}
