name: Sanity Preview Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Remove preview resources
        uses: dcilke/sanity-actions/cleanup@v0.0.45
        with:
          token: ${{ secrets.SANITY_DEPLOY_TOKEN }}
