name: Sanity Preview Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      # Cache dependencies
      - uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('${{ github.workspace }}/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # Install action dependencies
      - name: Install dependencies
        shell: bash
        run: |
          pnpm install

      - name: Remove preview resources
        uses: dcilke/sanity-actions/cleanup@v0.0.48
        with:
          token: ${{ secrets.SANITY_AUTH_TOKEN }}
